# --- MAPPO specific parameters ---
# Can reach 100% winrate within 500k steps

action_selector: "soft_policies"
mask_before_softmax: True

runner: "parallel"

buffer_size: 10
batch_size_run: 3  # num of env's
batch_size: 10

env_args:
  state_last_action: False # critic adds last action internally

# update the target network every {} training steps
target_update_interval_or_tau: 0

lr: 0.0005

obs_agent_id: False
obs_last_action: False  # True
obs_individual_obs: False

mac: "non_shared_mac"
agent: "th_rnn_ns"
agent_output_type: "pi_logits"
learner: "thesis_learner"
learner_log_interval: 2500
entropy_coef: 0.001
use_rnn: True
standardise_returns: False
standardise_rewards: True
q_nstep: 10 # 1 corresponds to normal r + gammaV
critic_type: "cv_critic"  # "ac_critic" 
# name: "debug_2svs1sc"
name: gae_test
eps_clip: 0.2

pi_epochs: 10
v_epochs: 5
aux_epochs: 4 # taken from: https://github.com/marlbenchmark/on-policy/blob/main/onpolicy/config.py
use_distil: True
# distil_beta: 0.01 # taken from: https://github.com/marlbenchmark/on-policy/blob/main/onpolicy/config.py
distil_beta: 1.0  # taken from DNA-PPO paper
use_huber_loss: True

runner_log_interval: 2500 # how often the agent's are tested and metrics are logged
log_interval: 15000
test_interval: 5000
t_max: 500
use_tensorboard: False

use_cuda: False
