# --- MAPPO specific parameters ---
# Reaches ~92% winrate after 630k timesteps currently, need to get to 100% to be on par with paper

action_selector: "soft_policies"
mask_before_softmax: True

runner: "parallel"

buffer_size: 10
batch_size_run: 10
batch_size: 10

env_args:
  state_last_action: False # critic adds last action internally

# update the target network every {} training steps
target_update_interval_or_tau: 0  # 0.01

lr: 0.0003 #5

obs_agent_id: False
obs_last_action: False
obs_individual_obs: False

mac: "non_shared_mac"
agent: "rnn_ns"
agent_output_type: "pi_logits"
learner: "ppg_learner"
entropy_coef: 0.01
use_rnn: True
standardise_returns: False
standardise_rewards: False
q_nstep: 10 # 1 corresponds to normal r + gammaV
critic_type: "cv_critic"
epochs: 15
eps_clip: 0.2
name: "mappg"

log_interval: 12500
test_interval: 12500
t_max: 1000000
